apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: eyabtest/my-todo-client:2.1.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
  labels:
    app: react-app
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30001
  selector:
    app: react-app