apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-js
  template:
    metadata:
      labels:
        app: node-js
    spec:
      containers:
      - name: node-js
        image: eyabtest/my-todo-server:4.0.0
        resources:
          limits:
            memory: "356Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: node-js-service
  labels:
    app: node-js
spec:
  type: NodePort
  selector:
    app: node-js
  ports:
  - port: 4000
    targetPort: 4000